#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Apr 10 10:13:27 2023

@author: vivek
"""

import cv2
import numpy as np
import os
import sys
import IPython.display as ipd
import pandas as pd
import matplotlib as plt


DATASET_PATH = "/home/vivek/Downloads/ICC WT20"

if __name__ == "__main__":
    
    files = os.listdir(DATASET_PATH)
    for file in files:
        
        video_path = os.path.join(DATASET_PATH, file)
        
        
        
        df = pd.DataFrame(video_path)
        
        ipd.Video(df)
        
        
        
        
        

